# Site settings
author: Saif Kasmani
title: Beginning of my Data Science journey.
header-img: img/home-bg.png
email: saifkasmani84@gmail.com
copyright_name: Saif Kasmani
description: > # this means to ignore newlines until "baseurl:"
  Blog 1
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saifzkb

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
